---
##
## This play runs on the source (production env)
## The data is pushed to the target (testing env)
##
## Requirements:
##  - the postgres system user on source can connect to the database on target
##  - the www-data system user on source can connect with ssh to target
##

##
## FIXME: this play should be run on the target host and then
## we'd use `delegate_to: source` only for the 2 ²:export tasks : pg_dump and rsync
##

- name: Load target info
  set_fact:
    target: "{{ hostvars[dolibarr_target_ansible_host] }}"

- name: Remove the dolibarr database if present on target
  become: true
  become_user: postgres
  postgresql_db:
    login_host: "{{ dolibarr_target_db_hostname }}"
    login_port: "{{ dolibarr_target_db_port }}"
    login_user: postgres
    name: "{{ dolibarr_target_db_database }}"
    state: absent

- name: Create an empty dolibarr database on target
  become: true
  become_user: postgres
  postgresql_db:
    login_host: "{{ dolibarr_target_db_hostname }}"
    login_port: "{{ dolibarr_target_db_port  }}"
    login_user: postgres
    name: "{{ dolibarr_target_db_database }}"
    owner: "{{ dolibarr_target_db_user }}"

- name: Export data from source to target
  become: true
  become_user: postgres
  shell: |
    set -o pipefail &&
    pg_dump "{{ dolibarr_db_database }}" \
      | psql  -h "{{ dolibarr_target_db_hostname }}" \
              -p "{{ dolibarr_target_db_port }}" \
              "{{ dolibarr_target_db_database }}"
  args:
    executable: /bin/bash

- name: Export the documents
  when: dolibarr_target_sync_documents|bool
  become: true
  become_user: www-data
  shell: "rsync -az {{ dolibarr_env_root }}/documents {{ dolibarr_target_ansible_host }}:{{ dolibarr_target_env_root }}/"

- name: Apply post-sync queries
  become: true
  become_user: postgres
  postgresql_query:
    db: "{{ dolibarr_target_db_database }}"
    login_host: "{{ dolibarr_target_db_hostname }}"
    login_user: postgres
    login_port: "{{ dolibarr_target_db_port }}"
    query: "{{ item }}"
  with_items: "{{ dolibarr_target_sync_post_queries }}"
